-- ════════════════════════════════════════════════════════════════════
-- EXPORTAR LA ESTRUCTURA DE LA BASE DE DATOS
--
-- La copia de seguridad (/gestion/copia) guarda los DATOS de las tablas.
-- Esta función describe la ESTRUCTURA: tablas y columnas, claves,
-- índices, permisos, seguridad por filas, vistas, funciones, disparadores
-- y la configuración de los almacenes de archivos. La copia la llama y
-- guarda el resultado dentro del mismo archivo.
--
-- Con las dos mitades se puede reconstruir el portal en un proyecto nuevo
-- de Supabase: primero se ejecuta la estructura, luego se restauran los
-- datos.
--
-- Solo la puede ejecutar el servidor del portal (service_role).
-- Se pega UNA VEZ en Supabase → SQL Editor → Run.
-- ════════════════════════════════════════════════════════════════════

CREATE OR REPLACE FUNCTION public.exportar_estructura()
RETURNS text
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $fn$
DECLARE
  sal   text := '';
  r     record;
  cols  text;
BEGIN
  sal := sal || '-- Estructura del portal APrieto · generada ' || now()::text || E'\n\n';

  -- 1. Extensiones
  sal := sal || E'-- ── Extensiones ──\n';
  FOR r IN SELECT extname, n.nspname FROM pg_extension e JOIN pg_namespace n ON n.oid = e.extnamespace
           WHERE extname <> 'plpgsql' ORDER BY extname LOOP
    sal := sal || format('CREATE EXTENSION IF NOT EXISTS %I WITH SCHEMA %I;', r.extname, r.nspname) || E'\n';
  END LOOP;

  -- 2. Secuencias sueltas (las de identidad van con su columna)
  sal := sal || E'\n-- ── Secuencias ──\n';
  FOR r IN SELECT c.relname FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
           WHERE n.nspname = 'public' AND c.relkind = 'S'
             AND NOT EXISTS (SELECT 1 FROM pg_depend d WHERE d.objid = c.oid AND d.deptype = 'i')
           ORDER BY c.relname LOOP
    sal := sal || format('CREATE SEQUENCE IF NOT EXISTS public.%I;', r.relname) || E'\n';
  END LOOP;

  -- 3. Tablas y columnas
  sal := sal || E'\n-- ── Tablas ──\n';
  FOR r IN SELECT c.oid, c.relname, c.relrowsecurity FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
           WHERE n.nspname = 'public' AND c.relkind IN ('r','p') ORDER BY c.relname LOOP
    SELECT string_agg(
             '  ' || quote_ident(a.attname) || ' ' || format_type(a.atttypid, a.atttypmod)
             || CASE a.attidentity WHEN 'a' THEN ' GENERATED ALWAYS AS IDENTITY'
                                   WHEN 'd' THEN ' GENERATED BY DEFAULT AS IDENTITY' ELSE '' END
             || CASE WHEN a.attgenerated = 's' THEN ' GENERATED ALWAYS AS (' || pg_get_expr(ad.adbin, ad.adrelid) || ') STORED'
                     WHEN ad.adbin IS NOT NULL THEN ' DEFAULT ' || pg_get_expr(ad.adbin, ad.adrelid) ELSE '' END
             || CASE WHEN a.attnotnull AND a.attidentity = '' THEN ' NOT NULL' ELSE '' END,
             E',\n' ORDER BY a.attnum)
      INTO cols
      FROM pg_attribute a
      LEFT JOIN pg_attrdef ad ON ad.adrelid = a.attrelid AND ad.adnum = a.attnum
     WHERE a.attrelid = r.oid AND a.attnum > 0 AND NOT a.attisdropped;
    sal := sal || format('CREATE TABLE IF NOT EXISTS public.%I (', r.relname) || E'\n' || coalesce(cols, '') || E'\n);\n';
  END LOOP;

  -- 4. Claves primarias, únicas y comprobaciones (antes que las ajenas)
  sal := sal || E'\n-- ── Claves y restricciones ──\n';
  FOR r IN SELECT cl.relname, co.conname, pg_get_constraintdef(co.oid) AS def
           FROM pg_constraint co JOIN pg_class cl ON cl.oid = co.conrelid JOIN pg_namespace n ON n.oid = cl.relnamespace
           WHERE n.nspname = 'public' AND co.contype IN ('p','u','c','x')
           ORDER BY cl.relname, co.contype, co.conname LOOP
    sal := sal || format('ALTER TABLE public.%I ADD CONSTRAINT %I %s;', r.relname, r.conname, r.def) || E'\n';
  END LOOP;
  FOR r IN SELECT cl.relname, co.conname, pg_get_constraintdef(co.oid) AS def
           FROM pg_constraint co JOIN pg_class cl ON cl.oid = co.conrelid JOIN pg_namespace n ON n.oid = cl.relnamespace
           WHERE n.nspname = 'public' AND co.contype = 'f'
           ORDER BY cl.relname, co.conname LOOP
    sal := sal || format('ALTER TABLE public.%I ADD CONSTRAINT %I %s;', r.relname, r.conname, r.def) || E'\n';
  END LOOP;

  -- 5. Índices que no vienen de una restricción
  sal := sal || E'\n-- ── Índices ──\n';
  FOR r IN SELECT i.indexdef FROM pg_indexes i
           WHERE i.schemaname = 'public'
             AND NOT EXISTS (SELECT 1 FROM pg_constraint co
                             JOIN pg_class ic ON ic.oid = co.conindid
                             WHERE ic.relname = i.indexname)
           ORDER BY i.tablename, i.indexname LOOP
    sal := sal || r.indexdef || E';\n';
  END LOOP;

  -- 6. Vistas
  sal := sal || E'\n-- ── Vistas ──\n';
  FOR r IN SELECT viewname, definition FROM pg_views WHERE schemaname = 'public' ORDER BY viewname LOOP
    sal := sal || format('CREATE OR REPLACE VIEW public.%I AS', r.viewname) || E'\n' || r.definition || E'\n';
  END LOOP;

  -- 7. Funciones propias (no las que traen las extensiones)
  sal := sal || E'\n-- ── Funciones ──\n';
  FOR r IN SELECT p.oid, p.proname FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
           WHERE n.nspname = 'public' AND p.prokind IN ('f','p')
             AND NOT EXISTS (SELECT 1 FROM pg_depend d WHERE d.objid = p.oid AND d.deptype = 'e')
           ORDER BY p.proname LOOP
    sal := sal || pg_get_functiondef(r.oid) || E';\n\n';
  END LOOP;

  -- 8. Disparadores
  sal := sal || E'-- ── Disparadores ──\n';
  FOR r IN SELECT pg_get_triggerdef(t.oid) AS def FROM pg_trigger t
           JOIN pg_class c ON c.oid = t.tgrelid JOIN pg_namespace n ON n.oid = c.relnamespace
           WHERE n.nspname = 'public' AND NOT t.tgisinternal ORDER BY c.relname, t.tgname LOOP
    sal := sal || r.def || E';\n';
  END LOOP;

  -- 9. Seguridad por filas y sus políticas
  sal := sal || E'\n-- ── Seguridad por filas (RLS) ──\n';
  FOR r IN SELECT c.relname FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
           WHERE n.nspname = 'public' AND c.relkind IN ('r','p') AND c.relrowsecurity ORDER BY c.relname LOOP
    sal := sal || format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY;', r.relname) || E'\n';
  END LOOP;
  FOR r IN SELECT * FROM pg_policies WHERE schemaname = 'public' ORDER BY tablename, policyname LOOP
    sal := sal || format('CREATE POLICY %I ON public.%I AS %s FOR %s TO %s%s%s;',
             r.policyname, r.tablename, r.permissive, r.cmd,
             array_to_string(r.roles, ', '),
             CASE WHEN r.qual IS NOT NULL THEN ' USING (' || r.qual || ')' ELSE '' END,
             CASE WHEN r.with_check IS NOT NULL THEN ' WITH CHECK (' || r.with_check || ')' ELSE '' END) || E'\n';
  END LOOP;

  -- 10. Permisos: se parte de cero y se dan los que hay
  sal := sal || E'\n-- ── Permisos de tablas ──\n';
  FOR r IN SELECT c.relname FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
           WHERE n.nspname = 'public' AND c.relkind IN ('r','p','v') ORDER BY c.relname LOOP
    sal := sal || format('REVOKE ALL ON public.%I FROM anon, authenticated, service_role;', r.relname) || E'\n';
  END LOOP;
  FOR r IN SELECT table_name, grantee, string_agg(privilege_type, ', ' ORDER BY privilege_type) AS privs
           FROM information_schema.role_table_grants
           WHERE table_schema = 'public' AND grantee IN ('anon','authenticated','service_role')
           GROUP BY table_name, grantee ORDER BY table_name, grantee LOOP
    sal := sal || format('GRANT %s ON public.%I TO %I;', r.privs, r.table_name, r.grantee) || E'\n';
  END LOOP;
  -- Permisos por columna (los que no vienen de un permiso de tabla entera)
  FOR r IN SELECT cp.table_name, cp.grantee, cp.privilege_type,
                  string_agg(quote_ident(cp.column_name), ', ' ORDER BY cp.column_name) AS columnas
           FROM information_schema.column_privileges cp
           WHERE cp.table_schema = 'public' AND cp.grantee IN ('anon','authenticated','service_role')
             AND NOT EXISTS (SELECT 1 FROM information_schema.role_table_grants g
                             WHERE g.table_schema = 'public' AND g.table_name = cp.table_name
                               AND g.grantee = cp.grantee AND g.privilege_type = cp.privilege_type)
           GROUP BY cp.table_name, cp.grantee, cp.privilege_type
           ORDER BY cp.table_name, cp.grantee, cp.privilege_type LOOP
    sal := sal || format('GRANT %s (%s) ON public.%I TO %I;', r.privilege_type, r.columnas, r.table_name, r.grantee) || E'\n';
  END LOOP;

  -- Permisos de ejecución de funciones
  sal := sal || E'\n-- ── Permisos de funciones ──\n';
  FOR r IN SELECT p.oid, p.proacl,
                  format('public.%I(%s)', p.proname, pg_get_function_identity_arguments(p.oid)) AS firma
           FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
           WHERE n.nspname = 'public' AND p.prokind IN ('f','p') AND p.proacl IS NOT NULL
             AND NOT EXISTS (SELECT 1 FROM pg_depend d WHERE d.objid = p.oid AND d.deptype = 'e')
           ORDER BY p.proname LOOP
    sal := sal || format('REVOKE ALL ON FUNCTION %s FROM PUBLIC, anon, authenticated, service_role;', r.firma) || E'\n';
    sal := sal || coalesce((
      SELECT string_agg(format('GRANT EXECUTE ON FUNCTION %s TO %s;', r.firma,
               CASE WHEN x.grantee = 0 THEN 'PUBLIC' ELSE quote_ident(x.grantee::regrole::text) END), E'\n')
        FROM aclexplode(r.proacl) x
       WHERE x.privilege_type = 'EXECUTE'
         AND (x.grantee = 0 OR x.grantee::regrole::text IN ('anon','authenticated','service_role'))
    ) || E'\n', '');
  END LOOP;

  -- 11. Almacenes de archivos (solo su configuración, no los archivos)
  sal := sal || E'\n-- ── Almacenes de archivos ──\n';
  IF to_regclass('storage.buckets') IS NOT NULL THEN
    FOR r IN EXECUTE 'SELECT id, name, public, file_size_limit, allowed_mime_types FROM storage.buckets ORDER BY id' LOOP
      sal := sal || format('INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types) VALUES (%L, %L, %L, %L, %L) ON CONFLICT (id) DO NOTHING;',
               r.id, r.name, r.public, r.file_size_limit, r.allowed_mime_types) || E'\n';
    END LOOP;
  END IF;

  RETURN sal;
END;
$fn$;

-- Solo el servidor del portal puede pedirla
REVOKE ALL ON FUNCTION public.exportar_estructura() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.exportar_estructura() TO service_role;

-- Comprobación: debe devolver un número de varios miles
SELECT length(public.exportar_estructura()) AS caracteres;
